### ISSUE TITLE
Client/server tweaks needed

### ISSUE THREAD

**Issue by AaronCQL** [CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15#103]
## Todos

- [x] Enable and use `username` field
- [x] Use `aggregate` to lookup actual users from questions and answers (https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/)
- [x] Forum page table should show exclude `slug`, include `user`, use correct format for `created`
- [x] Register should redirect user to forum page on success
- [x] Back button on question page should lead back to Forum page
- [ ] Back Button on profile page should lead back to Forum page (?)
